### PR TITLE
Did controller

### PR DESCRIPTION
**Pull request by julius-rennmann**
We talked about this section in the weekly meeting but I think I could not express myself clearly. Because of the DID spec we can not allow DID-URLs in the controller property. As I understand it we must conform to the standard and the DID controller must be a DID without path, query or fragments.
If I am wrong please correct me.

### CODE REVIEW

**Comment by ghost** [comment]
You are right, controller must not be a URL.

As I see, the only change needed here is that we do not include the permission name in the controller property. aka:

```json
{
    "id": "did:eosio:telos:example#owner",
    "controller": "did:eosio:telos:example2",
}
```

**Comment by julius-rennmann** [comment]
Could there maybe a confusion between the properties "id" and "controller" on the top-level DID document vs. inside the verification methods? Because on the top-level the "id" property can not be a DID-URL either. See following example:

DID document:

```json
{
  "@context": "https://www.w3.org/ns/did/v1",
  "id": "did:eosio:telos:example",
  "controller": "did:eosio:telos:example2",
  "...": "",
  "verificationMethod": [{
    "id": "did:eosio:telos:example#owner",
    "controller": "did:eosio:telos:example3",
    "...": "",
  }]
}
```

I do not have that much insight into the eosio permissioning yet, but coming from the DID spec this should be semantically correct.

**Comment by ghost** [comment]
"id" and "controller" cannot be a DID URL on both the DID document and the verification method objects. We don't need to repeat this in our DID method, it's quite clear in DID-core.

The only change I think we need to make in our EOSIO DID method specification is to remove the DID URL from the controller example. We do not need to remove all the content in this section and repeat the DID-core requirements.

**Comment by julius-rennmann** [comment]
OK, I think I understand what you are saying now. I will make a new PR just with the corrections. But two more questions on the issue:
Why only "MAY" on multiple authorization mechanisms?
The last line is a typo i presume, as it stands in direct conflict with the first line?

**Comment by ghost** [comment]
1. When an eosio root permission has one delegation, it is clear that another account controls this one. However if the root permission is e.g. 
```js
{
  threshold: 1,
  account: [ { perm: { account: "example2", perm: "active" }, weight: 1 } ]
  key: [ { key: "EOSkey1", weight: 1 } ]
}
```
then it is ambiguous if `example2` or the key controls the account. In this case I thought it would be up to the implementer. Happy to hear other suggestions.

2. Which line?

**Comment by julius-rennmann** [comment]
Thank you, I was not aware of the possibility to set accounts AND keys as delegations.

In that case I think it would be better to either never set the top level "controller" property as this will be redundant or even ambiguous (weights, keys) compared to the data in the "owner" key section of the verification methods. Or if we leave it I would suggest a "MUST" set always if root permissions are delegated to other accounts to satisfy the original intent from the DID spec.

**Comment by ghost** [comment]
Agreed. We should either never set it, or only set it if the permission is non-ambiguous (aka it delegates to one other account and has no other authorization).
For now I think, lets keep it simple and never set it. If you agree, please make the change.

**Pull request closed without merging**
